### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by thxu2** [kriasoft/aspnet-starter-kit#11]
Hi, when i run this on Mac, it don't start and throw exception 

 System.IO.FileNotFoundException' in System.IO.FileSystem.dll
fail: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60[13]

**Comment by koistya** [comment]
@thxu2 does it print what file is missing? The client-side portion of the app should be compiled into the /public/assets/` folder when you run either `npm run start` or `npm run build`..

**Comment by koistya** [comment]
I'm unable to replicate this issue. Can you please paste the full log here using the latest version of this boilerplate. Closing for now.
