### ISSUE TITLE
Question: What is the purpose?

### ISSUE THREAD

**Issue by amivit** [kriasoft/aspnet-starter-kit#19]
What's the point of bundling .net core together with frontend such as react/angular & webpack? Is it just to ease publication/development? Shouldn't they be mutually exclusive and communicating via. restful api's?

I notice these great boilerplates such as this where you combine both the server-side .net core together with webpack + angular/react for example. Is this to achieve intellisense, easier publication/distribution? Or what exactly is the purpose?

Thanks!

**Comment by koistya** [comment]
Yeah, it's easier to deploy your app this way, also, how would you test your app if the front-end part comes separately from the backend?
