### ISSUE TITLE
WebPack postcss config issue

### ISSUE THREAD

**Issue by NickSevens** [kriasoft/aspnet-starter-kit#21]
When creating a new project and running `node run`, i receive the following error:

> c:\Projects\MyApp>node run
> Starting 'start'...
> Starting 'clean'...
> Finished 'clean' after 11ms
> Starting 'appsettings'...
> Finished 'appsettings' after 9ms
> WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
> - configuration has an unknown property 'postcss'. These properties are valid:
>   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
>   For typos: please correct them.
>   For loader options: webpack 2 no longer allows custom properties in configuration.
>    Loaders should be updated to allow passing options via loader options in module.rules.
>    Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
>    plugins: {
>      new webpack.LoaderOptionsPlugin({
>        // test: /.xxx$/, // may apply this only for some modules
>        options: {
>          postcss: ...
>        }
>      })
>    }
>   at webpack (c:\Projects\MyApp\node_modules\webpack\lib\webpack.js:16:9)
>   at resolve (c:\Projects\MyApp\run.js:159:24)
>   at Promise.resolve.then.then.then (c:\Projects\MyApp\run.js:156:17)

**Comment by jacksomm** [comment]
There's a lot of discussion over here about this issue:
https://github.com/postcss/postcss-loader/issues/99

Took webpack down to beta 21 `npm install webpack@2.1.0-beta.21`  and was able to run node, but running into some kestrel web server errors now, not sure if they are correlated or not.  Might be better to fix the webpack.config.js references to postcss as suggested in the other thread.

**Comment by martinduo** [comment]
I have the same problem. I reinstalled webpack to version 1.13.2 and it runs. So I can begin to explore and understand it. First thing is that clicking the About button does nothing even though the address field shows http://localhost:3000/about, Clicking the Not Found button works with a 404 response. That's as far as I've got so far.

**Comment by code4aman** [comment]
I'm on win10 x64 and `webpack@2.1.0-beta.22` is OK for me, however on my (heavily modified) project setup - based on this awesome starter kit - I got it working with `webpack@2.1.0-beta.25`, BUT I have an issue with `postcss-import@8.1.(1|2)` on hot reload, so downgraded to it to `8.1.0` temporarily.
So, with `webpack@2.1.0-beta.23) and newer` try to move your postcss settings to `package.json` like shown [here](https://github.com/michael-ciniawsky/postcss-load-config#packagejson), I believe you only need a plugins section.
