### ISSUE TITLE
Errors in run.js

### ISSUE THREAD

**Issue by bmeverett** [kriasoft/aspnet-starter-kit#25]
When running `node run` I am getting a few errors.  When I first run the command I am getting this: 
![screen shot 2016-12-31 at 4 13 10 pm](https://cloud.githubusercontent.com/assets/3941006/21579265/18e6de00-cf74-11e6-8bdc-39e6014a198e.png)

I then put `'use strict';` at the top of run.js and am able to get further, but still run into this error: 
![screen shot 2016-12-31 at 4 14 58 pm](https://cloud.githubusercontent.com/assets/3941006/21579268/53dc2b28-cf74-11e6-84c3-d4b0049d2f33.png)

Not sure if these are just linting errors or what's going on.

**Comment by frenzzy** [comment]
[Requirements:](https://github.com/kriasoft/aspnet-starter-kit#prerequisites) [Node.js](https://nodejs.org/) v6 or newer

**Comment by bmeverett** [comment]
@frenzzy Sorry about that! I must've missed that. Upgrading fixed the issue. Thanks!
