### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by mwatts** [kriasoft/aspnet-starter-kit#9]
At least on my OSX install the following command fails.  I have attached all the information I know

the mentioned file " /Users/mwatts/tmp/try.aspnet-starter/MyApp/npm-debug.log" does not exist.

```
>npm start

[21:18:40] Starting 'start'...
Time: 5156ms
                           Asset     Size  Chunks             Chunk Names
    main.js?cbd653dd2e9a56f5e8e9   938 kB       0  [emitted]  main
main.js.map?cbd653dd2e9a56f5e8e9  1.08 MB       0  [emitted]  main
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn dotnet ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! app@1.0.0 start: `node tools/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@1.0.0 start script 'node tools/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mwatts/tmp/try.aspnet-starter/MyApp/npm-debug.log
```

**Comment by koistya** [comment]
@mwatts thanks for the report! There is also a way to launch the site directly by running:

```sh
$ cd server
$ node ../tools/bundle    # compile the JavaScript app
$ dotnet run              # launch ASP.NET Core app
```

This way it will give a more descriptive error message.

I just have updated the `tools/build.js` script, so that it will generate `server/appsettings.Production.json` and `server/appsettings.Development.json` files if they don't exist. These files are excluded from source control by default (see `.gitignore`), you may want to input your Facebook App ID, App Secret into one of these files.

I'm trying to find a way to how to make the app work if these values were not provided (see [`server/Startup.js#L69-80`](https://github.com/kriasoft/aspnet-starter-kit/blob/9cff388/server/Startup.cs#L69-L80). If you know a good solution, please send a [PR](https://help.github.com/articles/using-pull-requests/).

P.S.: There is more cool stuff coming to the project. Come back soon :)

**Comment by brentarias** [comment]
`npm start` also failed for me.  The alternate directions (launching `dotnet run`) also did not work.  Details:

 * Windows 10
 * node v6.2.1
 * dotnet 1.0.0-preview1-002702

The `dotnet restore` and `npm install` steps had worked successfully.  However, the `npm start` output was as shown below.  

    C:\repos\hub\aspnet-starter-kit>npm start

    > app@1.0.0 start C:\repos\hub\aspnet-starter-kit
    > node tools/start

    [10:57:02] Starting 'start'...
    Time: 4173ms
                              Asset     Size  Chunks             Chunk Names
        main.js?1213a06902a0826ef29e   937 kB       0  [emitted]  main
    main.js.map?1213a06902a0826ef29e  1.08 MB       0  [emitted]  main
    Error resolving full path []
    Error resolving full path []
    Project server (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
    Compiling server for .NETCoreApp,Version=v1.0
    Error resolving full path []
    Error resolving full path []

    Compilation succeeded.
        0 Warning(s)
        0 Error(s)

    Time elapsed 00:00:02.8413775


    info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
          User profile is available. Using 'C:\Users\baria\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
    Unhandled Exception: System.ArgumentException: The 'ClientId' option must be provided.
      at Microsoft.AspNetCore.Authentication.OAuth.OAuthMiddleware`1..ctor(RequestDelegate next, IDataProtectionProvider dataProtectionProvider, ILoggerFactory loggerFactory, UrlEncoder encoder, IOptions`1 sharedOptions, IOptions`1 options)
      at Microsoft.AspNetCore.Authentication.Facebook.FacebookMiddleware..ctor(RequestDelegate next, IDataProtectionProvider dataProtectionProvider, ILoggerFactory loggerFactory, UrlEncoder encoder, IOptions`1 sharedOptions, IOptions`1 options)
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
      at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
      at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next)
      at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
      at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
      at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
      at Server.Startup.Main()

The error and output was the same, regardless of whether I ran `npm start` or `dotnet run`.  The only difference is that `dotnet run` had the following additional pop-up message:

> **dotnet.exe has stopped working**
> A problem caused the program to stop working correctly.  Windows will close the program and notify you if a solution is available.

**Comment by koistya** [comment]
@mwatts, @brentarias this should be fixed via https://github.com/kriasoft/aspnet-starter-kit/commit/52decbc1195a627c7cc2b7eb2295a95c0d3ada30 - application was failing to start when Facebook App ID and App Secret values were missing in `appsettings.json`. Please re-open if there is still an issue.
